### ISSUE TITLE
SCSS files + overlay possible?

### ISSUE THREAD

**Issue by B-iggy** [zorgzerg/brackets-minimap#1]
Hey,

great that you made a minimap extension! Thumbs up. Can you tell when you will support scss files? For me it's broken. I can't scroll with the minimap to bottom. It's stopping at the middle. Like the math isn't right - calculating scss code height. Dunno.

And a nice to have request: Is it possible to make the minimap as an overlay like in sublime text? I saw in F12 that it's already position: absolute, but it's saving the width anyways. Would be great to save working space where ever possible.

**Comment by zorgzerg** [comment]
Hi.

Please update minimap to version 3.0.1, and try this.

Overlay is coming soon ;) I hope )))

**Comment by B-iggy** [comment]
Cool, thanks for quick fix!
The situation is now as the following:
1. In "No split" View it's working good. The scroll behavior. But not the theme. I love using the "Varz Dark" theme. So it is looking as you can see in first attachment.
Notice: I updated yesterday to Brackets 1.2. Maybe that is the problem cause I believe in 1.1 the minimap was dark too.
2. The tricky part starts at "Vertical Split" View. There are quite three random states at the moment.
#1: You select No Split -> Vertical Split -> Drag scss file from left to right:
Behavior like yesterday. It's scrolling to middle.
#2: Vertical Split -> restart Brackets -> Same as #1. Stop scrolling to middle.
#3: See second attachement. The Minimap Scroll overlay is one line height.

Weird. But maybe really because 1.2. Don't want to bother you. 

![themeprob](https://cloud.githubusercontent.com/assets/7815434/6247350/ce2fd098-b773-11e4-8b42-bd961bd5abab.PNG)
![minimap](https://cloud.githubusercontent.com/assets/7815434/6247357/e3f6fd7a-b773-11e4-9950-7a06e04e2e78.PNG)

**Comment by zorgzerg** [comment]
Please update minimap to version 3.1.0, and try this.
Split and theme support work is fine ;)

**Comment by B-iggy** [comment]
Version 3.1.0 was completley broken ;)
But I see you made it as overlay? That is nice. But the scroll behavior is reverse now and without a section highligther on the minimap.
See screenshot
![minimap](https://cloud.githubusercontent.com/assets/7815434/6328339/b0963562-bb66-11e4-9c70-028ead57b83c.PNG)
.

**Comment by zorgzerg** [comment]
Please update to actual version. It's fixed now

**Comment by zorgzerg** [comment]
I can close issue?

**Comment by B-iggy** [comment]
Sorry. Honestly I switched to Sublime back again, because of the bad speed performance with brackets.
But only for you, I reinstalled Brackets 1.1, uninstalled all extensions besides Minimap and tested it.
See my attachement for the outcome.
On splitview it's not getting the correct file. The scroll is weird too.

But you did a very great job with changelog fade in after update and double click feature. I don't know. I guess it is working on your system and others?
If you want you can close it.
![capture](https://cloud.githubusercontent.com/assets/7815434/6426916/ef7c1af4-bf70-11e4-83e1-13781e52d4a9.PNG)

**Comment by zorgzerg** [comment]
Hmmm... It's very strange ( 
I make many tests in vertical and horizontal split, and this work fine for me. Minimap correctly mirroring active pane, and disable for empty pane. I'm confused, but I will try to reproduce the bug to fix it.

Thanks for report
