### ISSUE TITLE
Scrolling down not cancelable

### ISSUE THREAD

**Issue by CagatayUlubay** [zorgzerg/brackets-minimap#10]
Hey there,

thank you for this nice plugin.

Currently there is an annonying feature. When you click on a spot, it's scrolling and scrolling and scrolling and you are like "Let me just drag-scroll to this position, I don't need this time consuming scroll-animation", but you can't cancel it. You have to wait, til it completes his animation to the clicked point and THEN you can do another action.

With the new update you can do SHIFT+Click to another point, so he cancel the other action and you just have to wait for the small SHIFT+Click animation, rather than the long one.. but it would be better if  you could cancel the other one if you just "Drag/Mouse_Down" the grey area and move it around.

Could I make clear my problem or should I try to reformulate it?

Kind regards :+1:

**Comment by zorgzerg** [comment]
Hi
Thx for bugreport. Now I change scrolling system in plugin, and it's will be next release. 
I know problem with unstopable animation and will fix it ;)

**Comment by CagatayUlubay** [comment]
Perfect,

thank you! :-) :v:

**Comment by zorgzerg** [comment]
Fixed. Update to ver. 3.2.4

**Comment by CagatayUlubay** [comment]
Works perfect, thank you!
