### ISSUE TITLE
Feature-Request: Transparency on mouseout should be optional

### ISSUE THREAD

**Issue by weblogixx** [zorgzerg/brackets-minimap#12]
Hi. First thank you for your great work, your plugin looks really nice! However, the transparency setting when not hovering the minimap should be optional, so that it stays on 100% even when not hovering the map (I think that this could be made configurable via the configuration?).

**Comment by zorgzerg** [comment]
Hi.
Update to latest version - 3.2.4 ;)

**Comment by weblogixx** [comment]
Works like a charm! Thank you!
