### ISSUE TITLE
Minimap locks up

### ISSUE THREAD

**Issue by jpietrangelo** [zorgzerg/brackets-minimap#13]
On my MacBook Pro, if I hold Ctrl and do a 2-finger swipe up/down on the minimap, I get to a point, after I've shrunk the map to it's smallest, where it says "x 1/NaN". When this happens I can no longer shrink/expand the map. Also, the code in the edit window disappears. It doesn't delete... it just can't be seen any longer. Requires reloading Brackets to fix.

**Comment by zorgzerg** [comment]
It's very-very strange. I was try repeat it from my PC, but it did not.

I haven't Mac, nothing to do testing (
