### ISSUE TITLE
Conflict with other extension

### ISSUE THREAD

**Issue by coreyavis** [zorgzerg/brackets-minimap#14]
This minimap extension conflicts with the minifier extension created by Wylst. When running the minifier extension the minimap extension has an error, which last time created a chain reaction of extensions getting errors.

**Comment by zorgzerg** [comment]
Hmm... Its very strange bug:
![image](https://cloud.githubusercontent.com/assets/1175579/7111089/02b0ce60-e1dd-11e4-9f6c-7582cb6dc485.png)

![image](https://cloud.githubusercontent.com/assets/1175579/7111083/ea37f232-e1dc-11e4-81fc-fee4f9c8c7b6.png)

UglifyJS is are component of minifier

require work wrong?!... I do not know what it is
