### ISSUE TITLE
Feature Request - Keyboard Shortcut To Show/Hide Minimap

### ISSUE THREAD

**Issue by ejfrancis** [zorgzerg/brackets-minimap#15]
Having a keyboard shortcut to open the minimap overlay instead of using the View>Show Minimap menu item with the mouse would make this less jarring to the workflow.

**Comment by Rayzor1** [comment]
I second this request. I work on a monitor turn vertical so its pretty narrow but I get to see lots of code. The minimap is great but real estate is valuable even with it ghosted its still there. If there was a shortcut I could bind a macro to my back button.

**Comment by zorgzerg** [comment]
Will be added in 3.2.5 soon

**Comment by zorgzerg** [comment]
Released. Update please

**Comment by kingluddite** [comment]
Has it been added yet?

**Comment by zorgzerg** [comment]
Yep
Show/hide toggle hotkey: Ctrl+`

**Comment by kingluddite** [comment]
Awesome. Thanks

**Comment by kingluddite** [comment]
Actually, I tried that shortcut and it toggles my console

https://i.imgur.com/G93EAP5.png

On Wed, May 11, 2016 at 7:31 AM, Phil Howley howley.phil@gmail.com wrote:

> Awesome. Thanks
> On May 11, 2016 6:43 AM, "zorgzerg" notifications@github.com wrote:
> 
> > Yep
> > Show/hide toggle hotkey: Ctrl+`
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/zorgzerg/brackets-minimap/issues/15#issuecomment-218462800

## 

Philip Howley - Web Developer Consultant
