### ISSUE TITLE
META REFRESH

### ISSUE THREAD

**Issue by inacio** [zorgzerg/brackets-minimap#17]
When you write this code the minimap interprets and executes an internal redirect in Bracket?

``` HTML
      <meta http-equiv="refresh" content="0;url=''" />
```

console error:
###### Failed to load URL data:text/html,chromewebdata with error:  (-3)

``` HTML
      <script>var url = 'data:text/html,chromewebdata';    var errorText = '';    var errorCode = '-3';    var msg = 'Failed to load URL ' + url + ' with error: ' + errorText + ' (' + errorCode + ')';    console.error(msg);</script>
```

![bug-bracket-with-minimap](https://cloud.githubusercontent.com/assets/1278678/7324302/a5f92b06-ea8b-11e4-9715-e078ada36e74.jpg)

**Comment by brennan-macaig** [comment]
Cannot replicate bug. Mind explaining more? Where exactly are you typing this? Are you sure it's this extension that's causing the error?
