### ISSUE TITLE
How to Disabled Smooth scroll?

### ISSUE THREAD

**Issue by evolutionjay2** [zorgzerg/brackets-minimap#18]
when I  cmd + click , and scrollback....
you know, I have a  very very long document, and the scroll back has long long time everytime.
can i just disable it?  this smooth scroll Wasted too much time!!!

and I  saw in your code, the animate function use setTimeout ?
Plz at least you want to use Window.requestAnimationFrame()

**Comment by brennan-macaig** [comment]
If you know a way to fix these issues - especially the latter - just submit a pull request.....?

**Comment by zorgzerg** [comment]
I changed my job, and now the time to develop minimap I have very little, unfortunately (( But soon everything will work out. Please wait a little longer.

**Comment by zorgzerg** [comment]
Hi. This will be fixed in 3.2.5 version soon

**Comment by zorgzerg** [comment]
Release. Update please
