### ISSUE TITLE
Theme & code folding question

### ISSUE THREAD

**Issue by Equals182** [zorgzerg/brackets-minimap#2]
Hello!
This is really great extension and I really like it.
I want to ask if it's possible to make it work with Code Folding extension and Themes?
I mean if i fold the code it wont be folded on minimap that eventually could be confusing.
Also it confuse me when syntax highlight is different from main window.
I should probably write it to Code Folding extension developer as well.

Thank you for your work

**Comment by zorgzerg** [comment]
Hi.

This problem really exists, unfortunately (( I'll try to find a solution. And highlighting too.

**Comment by Equals182** [comment]
Great! I hope you'll continue development of this extension.

**Comment by zorgzerg** [comment]
Highlighting fixed.
Please update minimap to version 3.0.1, and try this.

**Comment by Equals182** [comment]
Awesome! Thank you :)

**Comment by Equals182** [comment]
There are couple of bugs, I think. 
1. With this extension installed but turned off on Brackets start there is no scrollbar. I mean, when I start Brackets with Minimap turned off - I don't see scrollbar. It used to appear when I turn minimap on and then off again, but it doesn't work in this version.
2. When I turn minimap off it seems like events for minimap are still working. It's better to turn `.off` them with jQuery, because with files with 3k+ lines line in it, minimap works pretty slow and when I turn it off - it still works slow until I restart Brackets.

**Comment by zorgzerg** [comment]
1. Sorry, I forgot to uncomment some lines )))))
2. Yep, it's seen on large files

Now, I fixed it both. 

Thx, for you issues :)

**Comment by zorgzerg** [comment]
И это, Саш... Давай по русски, а? А то мой английский извэрибэд ))))))

**Comment by Equals182** [comment]
хаха)) ок, давай по-русски))

**Comment by zorgzerg** [comment]
Добро. В общем, попробуй 3.1.1, вроде б все заработало как надо. Вот CodeFolding пока победить не могу к сожалению, но не теряю надежд )

**Comment by Equals182** [comment]
Да, все круто! Ивенты отцепляются, скроллбар появляется) Здорово) Может написать разрабу Code Folding и предложить сотрудничество или типа того?

**Comment by zorgzerg** [comment]
Думал уже про это, если ничего не придумаю, так и сделаю )

**Comment by zorgzerg** [comment]
Добавлена поддержка Code Folding
Add support of Code Folding

Энжой, ёкарный бабай :)

**Comment by Equals182** [comment]
Нифига себе! Круто! Спасибо!)
Так у меня еще одно предложение седня созрело, но я подумал, что это надо разрабу другого приложения писать, а не тебе, так как логика выполнения зависит не от тебя. Если в кратце - поддержку Quick Search или хотя бы маломальскую совместимость.

**Comment by zorgzerg** [comment]
Ммм... так вроде скроллится все при поиске. Или я чего не так понял?

**Comment by Equals182** [comment]
Quick Search добавляет такую фишку.. если выделяешь слово - оно выделяет цветом все точные совпадения в документе и рисует желтенькие полоски на сроллбаре..) Но вообще им еще бы с Code Folding тоже интегрироваться) Короче я почти на 100% уверен - не к тебе)

**Comment by zorgzerg** [comment]
Угу, уже нашел. Ну сделать-то наверное можно... Для чего только? :) См. картинку :))
http://www.jablog.ru/wp-content/uploads/2011/12/Trolleybread.jpg

**Comment by Equals182** [comment]
Кхкхх)) Да не, я не думаю, что правильно будет твоему дополнению всегда пытаться подстроиться под другие, так что предложение закрывается)

**Comment by zorgzerg** [comment]
Ну откровенно говоря, оно и должно подстраиваться, чтобы полностью дублировать происходящее в основном редакторе. И смысл, в общем-то я уже увидел, и даже, возможно, попытаюсь реализовать, но только позже. Сейчас надо мной висят два проекта, которые никак нельзя провалить, так что временно только багфиксы, если таковые найдутся :)

**Comment by Equals182** [comment]
Да я и говорю, что это оно должно подстраиваться, так что как я уже писал - не к тебе это)
