### ISSUE TITLE
Scrollbar disappears when enabled

### ISSUE THREAD

**Issue by username1290** [zorgzerg/brackets-minimap#20]
There seems to be a conflict, since the scrollbar disappears when the extension is enabled

**Comment by zorgzerg** [comment]
No, this is not, conflict. Minimap replaces a scrollbar

**Comment by username1290** [comment]
Any way to have both?

**Comment by zorgzerg** [comment]
Why? Oo Minimap - is are scrollbar, but thicker )

**Comment by kuenzign** [comment]
A like this extension because it makes Brackets more like Sublime Text.  The only problem is that Sublime Text has both the minimap and the scrollbar.  Could you please look into incorporating this? :)

**Comment by zorgzerg** [comment]
Sorry, but there is no reason for this

**Comment by azlux** [comment]
I will give my opinion (and reopen this issue), the minimap is a scrollbar but try to select with ctrl+f a code, there are mark on the right where on your code there are matches. But with the minimap, the place do not correspond.

So without the scrollbar I’m lost when a search occurrences.

So I propose to override the search marks or keep the scroll bar with the minimap (can be an option)
