### ISSUE TITLE
Do I need to do anything to get my theme to work with it?

### ISSUE THREAD

**Issue by wormeyman** [zorgzerg/brackets-minimap#21]
https://github.com/Brackets-Themes/RubyBlue

I get a white preview:

![image](https://cloud.githubusercontent.com/assets/1795016/8040769/ee83377c-0dc7-11e5-904b-6b4566175368.png)

**Comment by wormeyman** [comment]
Could it be related to my theme using `less`?

**Comment by zorgzerg** [comment]
Hi. This will be fixed in version 3.2.5

**Comment by wormeyman** [comment]
:+1: Thanks.

**Comment by wormeyman** [comment]
By the way if you want to detach your fork from the original you can do that by asking Github support.

https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

**Comment by zorgzerg** [comment]
Released. Update please.

**Comment by zorgzerg** [comment]
thx for the advice )
