### ISSUE TITLE
Zoom issue with OSX

### ISSUE THREAD

**Issue by louy** [zorgzerg/brackets-minimap#22]
I was trying the new zoom feature (using CMD + scroll) and I reached a point where it says "x 1/NaN". Now I'm no longer able to scroll in or out. Looks like a script bug. Any ideas?

![untitled](https://cloud.githubusercontent.com/assets/349850/9403242/f5a96962-47ed-11e5-92ee-96afe93aa3a9.png)

**Comment by zorgzerg** [comment]
Hmmm... This has been fixed in 3.2.4 version. Please check your version and update if necessary
