### ISSUE TITLE
Permanent reserved UI space for minimap?

### ISSUE THREAD

**Issue by Hossrod** [zorgzerg/brackets-minimap#30]
THANK YOU for this extension!

One question, is there a way to have the minmap not be on top of the code editor, but in its own reserved space? I don't want code to "go under" it. I would like word-wrap to happen at the left edge of the minimap. Hope that makes sense. :)

Thanks!

**Comment by odysseyalive** [comment]
I'm rather new to Brackets myself.  I've installed many of the plugins, such as Minimap that mimic features I use in Sublime.  Unfortunately there is no place that I can see where I can manage the right hand margin for text wrapping.  It would be great to be able to prevent code from hiding behind Minimap.  Opening and closing it will be a pain.

**Comment by zorgzerg** [comment]
@Hossrod, @bridgesense 
Unfortunately this is impossible. 
Try double-click on the slider. This will toggle the autohide minimap, and that should satisfy you. Please read the readme carefully.

**Comment by odysseyalive** [comment]
I will.  But thanks for the tip.  That works out perfectly.
