### ISSUE TITLE
Shortcut key Issue hide/show ctrl+

### ISSUE THREAD

**Issue by ArsalanWahid** [zorgzerg/brackets-minimap#32]
The shortcut key for showing or hiding the minimap conflicts with the shortcut key ctrl++ in the view menu for increasing/decreasing font size 

Thanks

**Comment by zorgzerg** [comment]
Minimap does not use a combination of "Ctrl++" Use "Ctrl + `"

**Comment by ArsalanWahid** [comment]
Oh I'll try it out thanks
