### ISSUE TITLE
html script code runs on latest versions with no file extension.

### ISSUE THREAD

**Issue by stypr** [zorgzerg/brackets-minimap#33]
if there's no extension on the file and html script code is inserted, the script gets executed without any filters.

I'm currently using latest edition of Brackets version (tested on OSX and Windows), with the latest version of Minimap.

the way to trigger the problem is as follows:

1) create a filename with no extension (example, 'testtest')
2) insert the html script tag with appropriate javascript codes. (example, '')
3) open the file in brackets.

this bug might lead to security problems (precisely XSS/CSRF problems).

![2015-11-20 4 40 08](https://cloud.githubusercontent.com/assets/6625978/11294490/4839f178-8fa7-11e5-94ba-4590dee835c4.png)

**Comment by zorgzerg** [comment]
This will be fixed in v3.2.6. Coming soon
