### ISSUE TITLE
Connecting to http://online-dnbard.rhcloud.com/

### ISSUE THREAD

**Issue by neodaemerung** [zorgzerg/brackets-minimap#36]
Why this extension is trying to connect to:
http://online-dnbard.rhcloud.com/ ?

![brackets_2016-01-30_15-35-45](https://cloud.githubusercontent.com/assets/7332137/12698146/96bc4ee8-c767-11e5-94f7-77c18e993ce1.png)

**Comment by Murazaki** [comment]
I assume it is too get the number of users using the app through the Brackets Extension Rating : https://github.com/dnbard/brackets-extension-rating

**Comment by zorgzerg** [comment]
Yep, it's true
