### ISSUE TITLE
Cannot disable auto-hiding

### ISSUE THREAD

**Issue by JannikHv** [zorgzerg/brackets-minimap#46]
I really don't know how to disable the minimaps auto-hiding. Otherwise it works perfectly for me and really helps me codin.g

**Comment by zorgzerg** [comment]
Hi. Just use double-click on minimap slider

**Comment by JannikHv** [comment]
I'm pretty retarded, thanks for the tip, everything works! :)

**Comment by zorgzerg** [comment]
You are welcome )
