### ISSUE TITLE
Turn Overlay Off?!

### ISSUE THREAD

**Issue by KiereKat** [zorgzerg/brackets-minimap#5]
I know it saves space but I cannot click on code that is under the overlay, it is making me crazy. Please add the minimap on the side as an option.

**Comment by zorgzerg** [comment]
Yep, some times is make me crazy too ))))
And i do it... but later. Please wait ;)

**Comment by zorgzerg** [comment]
Fixed, update to 3.1.6 version please. And thx the for issue

**Comment by KiereKat** [comment]
Thanks so much! I love the solution you came up with.
