### ISSUE TITLE
when click the minimap rectangle it jumps

### ISSUE THREAD

**Issue by darkyelox** [zorgzerg/brackets-minimap#6]
Hello, i don't know if only happens to me, but when i click the minimap rectangle the idea is to move that rectangle accordingly to that pointer position but it jumps to a predetermined position  (for example 20px over mouse actual position), no matter if i don't make any drag, it jumps, that is annoying or i'm wrong?

**Comment by zorgzerg** [comment]
Hi.
It is not bug, this is - feature implementation ))) but i fix it later. Please wait

**Comment by zorgzerg** [comment]
Fixed, please update to 3.1.6 version. The 4 issue )
