### ISSUE TITLE
Copying page.

### ISSUE THREAD

**Issue by Athax** [zorgzerg/brackets-minimap#7]
It seems like minimap, makes an exacy copy of what you wrote in your file, and put it right under the orginal text..

Like if you copied everything you wrote, and just CTRL-V it right under what you just wrote.

**Comment by zorgzerg** [comment]
What do you mean? Explain more please

**Comment by Athax** [comment]
Ever since i installed minimap, this bug appers sometimes. It dublicates what is already written.

**Comment by zorgzerg** [comment]
Hmmm... So all right. Minimap should display all your smaller text right. To save space, it is displayed on top of the main text. And what functionality you'd expect from the expansion? Have you read the description?

**Comment by zorgzerg** [comment]
My English isn't very good and I could have misunderstood

**Comment by Athax** [comment]
No what it seems to do is, to take the the whole page and copy all of the content, and put it right under the already written content in the same page.

**Comment by zorgzerg** [comment]
Make screenshot please, I need to see it

**Comment by Athax** [comment]
I will do it as soon as it happens again. :)
