### ISSUE TITLE
small bug.

### ISSUE THREAD

**Issue by parsisan** [zorgzerg/brackets-minimap#8]
thats great plugin, and thanks about that,
but i think that have some problem,
when you type your code mini map will update...
this make my typing slow and with delay...
other thing is opening big files. file cant open fast as without this plugin.

i think if you capture code screen as a bitmap and just get scroll position to that all will be fast.
thanks again.

**Comment by zorgzerg** [comment]
Yep. 
Unfortunately you are right, with large files running slow. 
While I have no idea how to capture an image. Can you suggest something?

**Comment by zorgzerg** [comment]
Fixed. Please update to last version 3.2.0
